### ISSUE TITLE
Shader seems not working under 0.9.0

### ISSUE THREAD

**Issue by musiko** [Flightphase/ofxProjectorBlend#2]
There is no shader compilation error, but no blending appears.
No idea what is wrong after several attempts, would you advise?
(Windows 7 + 0.9.0 + VS2015)

**Comment by javl** [comment]
@musiko Just posting to let you know ofxProjectBlend is working again in the current `0.9.2` release (looking at the changelog I think the error was in OF and it was fixed in `0.9.1`),
